version: "3.2"
services:
  nginx:
    image: registry.cn-zhangjiakou.aliyuncs.com/bisheng/nginx:free
    container_name: nginx
    privileged: true
    volumes:
    - ${basedir}/service/nginx/config:/config:rw
    - ${basedir}/service/nginx/temp:/temp:rw
    - ${basedir}/service/keys/keys:/keys:rw
    ports:
    - 80:80
    - 443:443
    restart: on-failure
    networks:
    - bisheng
  dgraphZero:
    image: dgraph/dgraph:v1.0.5
    container_name: dgraphZero
    privileged: true
    volumes:
      - ${basedir}/service/dgraph:/dgraph:rw
#    ports:
#      - 5080:5080
#      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
    networks:
      bisheng:
        aliases:
        - dgraphZero
  dgraphServer:
    image: dgraph/dgraph:v1.0.5
    container_name: dgraphServer
    privileged: true
    volumes:
      - ${basedir}/service/dgraph:/dgraph:rw
#    ports:
#      - 8080:8080
#      - 9080:9080
    restart: on-failure
    command: dgraph server --whitelist  172.17.0.0:172.20.0.0 --my=dgraphServer:7080 --lru_mb=2048 --zero=dgraphZero:5080
    networks:
      bisheng:
        aliases:
        - dgraphServer
  dgraphRatel:
    image: dgraph/dgraph:v1.0.5
    container_name: dgraphRatel
    privileged: true
    volumes:
       - ${basedir}/service/dgraph:/dgraph:rw
#    ports:
#      - 8000:8000
    restart: on-failure
    command: dgraph-ratel
    networks:
      bisheng:
        aliases:
        - dgraphRatel
  mongod:
    image: mongo:3.6
    container_name: mongod
    privileged: true
    volumes:
       - ${basedir}/service/mongod/db/:/data/db:rw
       - ${basedir}/service/mongod/config/:/data/configdb:rw
       - ${basedir}/service/mongod/log/:/data/log:rw
#    ports:
#      - 27017:27017
    restart: on-failure
    command: --config /data/configdb/mongod.conf
    networks:
      bisheng:
        aliases:
        - mongod


  redis:
    image: redis:4.0
    container_name: redis
    privileged: true
    volumes:
       - ${basedir}/service/redis/db:/data:rw
       - ${basedir}/service/redis/config/redis.conf:/usr/local/etc/redis/redis.conf:rw
#    ports:
#      - 6379:6379
    restart: on-failure:10
    command: /usr/local/etc/redis/redis.conf
    networks:
      bisheng:
        aliases:
        - redis


  rabbit:
    image: rabbitmq:3.6
    container_name: rabbit
    privileged: true
    volumes:
       - ${basedir}/service/rabbitmq/data/:/var/lib/rabbitmq/mnesia:rw
       - ${basedir}/service/rabbitmq/config:/etc/rabbitmq:rw
#    ports:
#      - 4369:4369
#      - 5671-5672:5671-5672
#      - 15672:15672
#      - 25672:25672
    restart: on-failure:10
    networks:
      bisheng:
        aliases:
        - rabbit

  minio:
    image: minio/minio
    container_name: minio
    privileged: true
    volumes:
      - ${basedir}/service/minio/data:/data:rw
      - ${basedir}/service/minio/config:/root/.minio:rw
    environment:
      MINIO_ACCESS_KEY: 9QPAQ65R1SO1NDHNYESN
      MINIO_SECRET_KEY: X9MquX/OTU35GLApKJ8tEMqBcTcXc4WSKigkroUI
#    ports:
#      - 9000:9000
    restart: on-failure
    command: server /data
    networks:
      bisheng:
        aliases:
        - minio

  search:
    image: registry.cn-zhangjiakou.aliyuncs.com/bisheng/search:free
    container_name: search
    volumes:
      - ${basedir}/service/elasticsearch/data:/workspace/data:rw
      - ${basedir}/service/elasticsearch/logs:/workspace/logs:rw
#    ports:
#      - 9200:9200
#      - 9300:9300
    user: elsearch
    restart: on-failure:10
    networks:
      bisheng:
        aliases:
        - search
  tootls:
    image: registry.cn-zhangjiakou.aliyuncs.com/bisheng/tootls:${tag}
    container_name: tootls
    privileged: true
    volumes:
    - ${basedir}:/workspace
    restart: on-failure:10
    networks:
      bisheng:
        aliases:
        - tools
networks:
  bisheng:
    external: true
