rabbitmq:
  host: rabbit  # rabbitmq的主机名或IP
  port: 5672   # rabbitmq的端口
  user: guest   # rabbitmq的用户名，默认值为 guest,根据各自的情况进行更改
  password: guest # rabbitmq的用户名，默认值为 guest,根据各自的情况进行更改
minio:
  endpoint: minio:9000   # minio的主机名或IP,根据自己的情况修改
#  publicendpoint: oss-cn-beijing.aliyuncs.com #针对实际部署时s3内外网的区别，
  ak: 9QPAQ65R1SO1NDHNYESN  # minio 的ak ,根据自己的情况修改
  sk: X9MquX/OTU35GLApKJ8tEMqBcTcXc4WSKigkroUI  # minio的sk,根据自己的情况修改
  secure: false
  uploadbucket: upload
  draftbucket: draft
  staticbucket: static
  #dnslookup: true
  #region: oss-cn-beijing
statichost:  /s3 # minio的资源访问地址，根据自己情况修改
dgrpah:
  addr: dgraphServer:9080  # dgraph的主机名或IP,根据自己的情况修改,端口一般是默认值
mongodb:
  url: mongod  # mongodb的主机名或IP,根据自己的情况修改
  db: docs
redis:
  url: redis:6379   # minio的主机名或IP,根据自己的情况修改,端口一般是默认值
  db: 0
elasticsearch:
  url: search:9200
  enable: false
editorurl: http://HOST/apps/editor
wechat:
  openwebsiteapp: # 微信开放平台网站应用
    appid: wxffffffffffffffff
    appsecret: ffffff
  openiosapp: # 微信开放平台ios应用
    appid: wxffffffffffffffff
    appsecret: ffffff
  openandroidapp: # 微信开放平台android应用
    appid: wxffffffffffffffff
    appsecret: ffffff
  mpofficialaccount:  # 微信公众平台公众号
    appid: wxffffffffffffffff
    appsecret: ffffff
  mpapplet: # 微信公众平台小程序
    appid: wxffffffffffffffff
    appsecret: ffffff
